#!/bin/bash

# publish operation must be done from David's home desktop
if [ `hostname` != "desktop-dell" ];then
  echo "Error: Must be executed from David's home desktop"
  exit
fi

# get version name
version=`grep version source/conf.py | grep = | awk -F\' '{print $2}'`
filename=pythtb_website_$version.tar

cd build/html
tar -hcvf $filename *

rsync -v --progress $filename physsun.rutgers.edu:~/pu/pythtb-master/

rm $filename
