#!/bin/bash

# which python to use in generating .tar.gz, .exe
host="`hostname`"
if [ $host = "coh" ];then
    PYTHON_FOR_BIN=python
else
    PYTHON_FOR_BIN=python
fi	    

# temporary folders
MISC=source/misc
EXAMPLES=source/examples

# clear up temporary folders
rm -rf $MISC
mkdir -p $MISC
rm -rf $EXAMPLES
mkdir -p $EXAMPLES

# need this folder so that you don't get warning
mkdir source/_static

# construct source tarball and put it in misc folder
rm -rf ../dist
rm ../MANIFEST
(cd .. ; $PYTHON_FOR_BIN setup.py sdist --format=gztar)
(cd .. ; $PYTHON_FOR_BIN setup.py sdist --format=zip)
cp ../dist/*.tar.gz $MISC
cp ../dist/*.zip $MISC
rm -rf ../dist

# copy more stuff to misc folder
cp ../LICENSE $MISC
cp ../dev/talk/pythtb-talk.pdf $MISC
cp ../dev/formalism/pythtb-formalism.pdf $MISC
cp local/release/ver_*/*.tar.gz $MISC
cp local/w90_example/wannier90_example.tar.gz $MISC

# copy all example files
rsync -a ../examples/ $EXAMPLES/

# make simple figure for main page
# ln -s ../examples/pythtb.py source/simple_fig/pythtb.py
# ln -s ../../matplotlibrc source/simple_fig/matplotlibrc
(cd source/simple_fig ; python3 simple_fig.py)

# now create website using sphinx
make html
